apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bpq6f9dck-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:e9fec4cbd5a4de176f2822468370d0ee3d2468df@sha256:ba243aeaaa586e88a03f8757454787a422aa939cfa2c7b8f490228bfbf5c6cc6
          name: container-image
