apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bpq6f9dck-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bpq6f9dck-dotnet-basic 
  name: bpq6f9dck-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bpq6f9dck-dotnet-basic 
